# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ed55b97919b09079e5b0f84ea5f8b3dc29e2e7725f72c4c593bf531bcc1695979997e8b45816c90cda0d5cdf2853641d1b4fbeed8b02ffea95d2855afa7b9c2

test:
  secret_key_base: eecb413616e588270c34431179abc3a472a5e47cb85e889b79e7a6f4622fc5d72cbe8b4f062c72aff4ab492a83d75fdb264c07870452fde4e85c89359370be96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
